// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerfectKeyV1.Infrastructure.Persistence;

#nullable disable

namespace PerfectKeyV1.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208031017_AddNewColumnToUserTable")]
    partial class AddNewColumnToUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AreaAlias")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AreaAlias");

                    b.Property<string>("AreaAvatar")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AreaAvatar");

                    b.Property<string>("AreaCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AreaCode");

                    b.Property<string>("AreaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("AreaDescription");

                    b.Property<string>("AreaName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("AreaName");

                    b.Property<string>("AreaType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("AreaType");

                    b.Property<Guid?>("AreaTypeGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AreaTypeGuid");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Guid");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("Height");

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HotelCode");

                    b.Property<Guid>("HotelGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HotelGuid");

                    b.Property<int>("HotelId")
                        .HasColumnType("int")
                        .HasColumnName("HotelId");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("LastModify")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModify");

                    b.Property<Guid?>("ParentGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ParentGuid");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("Parent");

                    b.Property<int?>("PositionX")
                        .HasColumnType("int")
                        .HasColumnName("PositionX");

                    b.Property<int?>("PositionY")
                        .HasColumnType("int")
                        .HasColumnName("PositionY");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("Width");

                    b.HasKey("Id");

                    b.HasIndex("AreaTypeGuid");

                    b.HasIndex("HotelGuid");

                    b.HasIndex("ParentGuid");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.AreaType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Code");

                    b.Property<string>("Descriptions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Descriptions");

                    b.Property<string>("GroupCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GroupCode");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Guid");

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HotelCode");

                    b.Property<Guid>("HotelGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HotelGuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("Code", "HotelGuid")
                        .IsUnique();

                    b.ToTable("AreaType", (string)null);
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.Element", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Alias");

                    b.Property<Guid>("AreaGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("AreaGuid");

                    b.Property<int>("AreaId")
                        .HasColumnType("int")
                        .HasColumnName("AreaId");

                    b.Property<int?>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacity");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Color");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Description");

                    b.Property<Guid?>("DockGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DockGuid");

                    b.Property<string>("GroupElements")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("GroupElements");

                    b.Property<Guid?>("GroupElementsGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GroupElementsGuid");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Guid");

                    b.Property<int?>("Height")
                        .HasColumnType("int")
                        .HasColumnName("Height");

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("HotelCode");

                    b.Property<Guid>("HotelGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HotelGuid");

                    b.Property<string>("Icon")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("Icon");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsOccupied")
                        .HasColumnType("bit")
                        .HasColumnName("IsOccupied");

                    b.Property<DateTime?>("LastModify")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModify");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<int>("PositionX")
                        .HasColumnType("int")
                        .HasColumnName("PositionX");

                    b.Property<int>("PositionY")
                        .HasColumnType("int")
                        .HasColumnName("PositionY");

                    b.Property<int>("Rotation")
                        .HasColumnType("int")
                        .HasColumnName("Rotation");

                    b.Property<string>("Settings")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Settings");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Type");

                    b.Property<int?>("Width")
                        .HasColumnType("int")
                        .HasColumnName("Width");

                    b.HasKey("Id");

                    b.HasIndex("AreaGuid");

                    b.ToTable("Elements");
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AutoId")
                        .HasColumnType("int")
                        .HasColumnName("AutoID");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Ma");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<string>("DBName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DBName");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Email");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayKetThuc");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GUID");

                    b.Property<string>("HotelAvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HotelAvatarUrl");

                    b.Property<string>("HotelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("HotelName");

                    b.Property<string>("IPAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("IPAddress");

                    b.Property<string>("IPLAN_Server")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IPLAN_Server");

                    b.Property<string>("IP_VPN_FO")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IP_VPN_FO");

                    b.Property<string>("IP_VPN_ISS")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("IP_VPN_ISS");

                    b.Property<string>("ISS_DBName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ISS_DBName");

                    b.Property<string>("ISS_IPAddress")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("ISS_IPAddress");

                    b.Property<int?>("IsAutoUpdateOTA")
                        .HasColumnType("int")
                        .HasColumnName("IsAutoUpdateOTA");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("GhiChu");

                    b.Property<string>("OTATimesAuto")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("OTATimesAuto");

                    b.Property<string>("PKMTablet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PKMTablet");

                    b.Property<Guid?>("ParentGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ParentGUID");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("Parent");

                    b.Property<int?>("Sequency")
                        .HasColumnType("int")
                        .HasColumnName("Sequency");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("NgayBatDau");

                    b.Property<Guid?>("UserGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.HasIndex("ParentGuid");

                    b.ToTable("DATA_KhachSan", (string)null);
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.LoginSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Browser")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Browser");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DeviceInfo");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("IpAddress");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<bool>("IsRememberMe")
                        .HasColumnType("bit")
                        .HasColumnName("IsRememberMe");

                    b.Property<bool>("IsTwoFactorVerified")
                        .HasColumnType("bit")
                        .HasColumnName("IsTwoFactorVerified");

                    b.Property<DateTime?>("LastActivity")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastActivity");

                    b.Property<DateTime?>("LastModify")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModify");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Location");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LoginTime");

                    b.Property<DateTime?>("LogoutTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("LogoutTime");

                    b.Property<string>("OperatingSystem")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("OperatingSystem");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("RefreshToken");

                    b.Property<string>("SessionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SessionType");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("Token");

                    b.Property<DateTime?>("TokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("TokenExpiry");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("UserAgent");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("LastActivity");

                    b.HasIndex("RefreshToken")
                        .IsUnique();

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId", "IsActive");

                    b.ToTable("LoginSessions", (string)null);
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Alias");

                    b.Property<string>("AvatarDes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AvatarDes");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("AvatarUrl");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Code");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comments");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("FullName");

                    b.Property<int?>("GroupParent")
                        .HasColumnType("int")
                        .HasColumnName("GroupParent");

                    b.Property<Guid?>("GroupParentGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("GroupParentGuid");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Guid");

                    b.Property<string>("JobTitle")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JobTitle");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastLogin");

                    b.Property<DateTime?>("LastModify")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModify");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Mobile");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ResetToken");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("ResetTokenExpiry");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<int>("TwoFactorEnabled")
                        .HasColumnType("int")
                        .HasColumnName("TwoFactorEnabled");

                    b.Property<string>("TwoFactorRecoveryCodes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TwoFactorRecoveryCodes");

                    b.Property<string>("TwoFactorSecret")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TwoFactorSecret");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserName");

                    b.Property<int?>("UserType")
                        .HasColumnType("int")
                        .HasColumnName("UserType");

                    b.Property<DateTime?>("ValidTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidTime");

                    b.HasKey("Id");

                    b.ToTable("DATA_Users", (string)null);
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.UserHotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Comments");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Guid");

                    b.Property<string>("HotelCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("HotelCode");

                    b.Property<Guid>("HotelGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("HotelGUID");

                    b.Property<DateTime?>("LastModify")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModify");

                    b.Property<int>("Status")
                        .HasColumnType("int")
                        .HasColumnName("Status");

                    b.Property<string>("UserBO")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserBO");

                    b.Property<Guid?>("UserCreatedGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserCreatedGuid");

                    b.Property<string>("UserERP")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserERP");

                    b.Property<string>("UserFO")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserFO");

                    b.Property<Guid>("UserGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserGuid");

                    b.Property<string>("UserHR")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserHR");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("UserID");

                    b.Property<string>("UserPOS")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("UserPOS");

                    b.Property<DateTime?>("ValidDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ValidDate");

                    b.HasKey("Id");

                    b.HasIndex("HotelGuid");

                    b.HasIndex("UserGuid", "HotelGuid")
                        .IsUnique();

                    b.ToTable("DATA_User_Hotels", (string)null);
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.Area", b =>
                {
                    b.HasOne("PerfectKeyV1.Domain.Entities.AreaType", "AreaTypeNavigation")
                        .WithMany("Areas")
                        .HasForeignKey("AreaTypeGuid")
                        .HasPrincipalKey("Guid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PerfectKeyV1.Domain.Entities.Hotel", "Hotel")
                        .WithMany("Areas")
                        .HasForeignKey("HotelGuid")
                        .HasPrincipalKey("Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectKeyV1.Domain.Entities.Area", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentGuid")
                        .HasPrincipalKey("Guid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AreaTypeNavigation");

                    b.Navigation("Hotel");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.Element", b =>
                {
                    b.HasOne("PerfectKeyV1.Domain.Entities.Area", "Area")
                        .WithMany("Elements")
                        .HasForeignKey("AreaGuid")
                        .HasPrincipalKey("Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.Hotel", b =>
                {
                    b.HasOne("PerfectKeyV1.Domain.Entities.Hotel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentGuid")
                        .HasPrincipalKey("Guid")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.LoginSession", b =>
                {
                    b.HasOne("PerfectKeyV1.Domain.Entities.User", "User")
                        .WithMany("LoginSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.UserHotel", b =>
                {
                    b.HasOne("PerfectKeyV1.Domain.Entities.Hotel", "Hotel")
                        .WithMany("UserHotels")
                        .HasForeignKey("HotelGuid")
                        .HasPrincipalKey("Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerfectKeyV1.Domain.Entities.User", "User")
                        .WithMany("UserHotels")
                        .HasForeignKey("UserGuid")
                        .HasPrincipalKey("Guid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.Area", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Elements");
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.AreaType", b =>
                {
                    b.Navigation("Areas");
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.Hotel", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Children");

                    b.Navigation("UserHotels");
                });

            modelBuilder.Entity("PerfectKeyV1.Domain.Entities.User", b =>
                {
                    b.Navigation("LoginSessions");

                    b.Navigation("UserHotels");
                });
#pragma warning restore 612, 618
        }
    }
}
